#include<iostream>
#include<stdexcept>
using namespace std;
class Test
{
	int arr[10],n,s;
	public:
	void check()
	{
		cout<<"enter array size:";
		cin>>n;
		cout<<"enter array elements:"<<endl;
		for(int i=0;i<n;i++)
		cin>>arr[i];
		cout<<"enter which location number do you want to display:";
		cin>>s;
		
		try
		{
			if(s<0||s>=n)
			throw range_error("the array index range is not a valid\n");
			cout<<"the location value is:"<<arr[s]<<endl;
		}catch(range_error&error)
		{
			cout<<"exception occured:"<<error.what();
			
		} 
	}
};
int main()
{
	Test t;
	t.check();
	return 0;
	
}
